# -*- coding: utf-8 -*-

STATES = {
    'NONDISTRIBUTED': '98',
    'ARMED FORCES - EUROPE': 'AE',
    'ALASKA': 'AK',
    'ALABAMA': 'AL',
    'ARKANSAS': 'AR',
    'AMERICAN SAMOA': 'AS',
    'ARIZONA': 'AZ',
    'BRITISH COLUMBIA (CANADA)': 'BC',
    'CALIFORNIA': 'CA',
    'COLORADO': 'CO',
    'CONNECTICUT': 'CT',
    'DISTRICT OF COLUMBIA': 'DC',
    'DELAWARE': 'DE',
    'FLORIDA': 'FL',
    'GEORGIA': 'GA',
    'GABON': 'GB',
    'GERMANY': 'GM',
    'GUAM': 'GU',
    'HAWAII': 'HI',
    'IOWA': 'IA',
    'IDAHO': 'ID',
    'ILLINOIS': 'IL',
    'INDIANA': 'IN',
    'JAPAN': 'JA',
    'KANSAS': 'KS',
    'KENTUCKY': 'KY',
    'LOUISIANA': 'LA',
    'MASSACHUSETTS': 'MA',
    'MARYLAND': 'MD',
    'MAINE': 'ME',
    'MARSHALL ISLANDS': 'MH',
    'MICHIGAN': 'MI',
    'MINNESOTA': 'MN',
    'MISSOURI': 'MO',
    'NORTHERN MARIANA ISLANDS': 'MP',
    'MISSISSIPPI': 'MS',
    'MONTANA': 'MT',
    'NORTH CAROLINA': 'NC',
    'NORTH DAKOTA': 'ND',
    'NEBRASKA': 'NE',
    'NEW HAMPSHIRE': 'NH',
    'NEW JERSEY': 'NJ',
    'NEW MEXICO': 'NM',
    'NEVADA': 'NV',
    'NEW YORK': 'NY',
    'OHIO': 'OH',
    'OKLAHOMA': 'OK',
    'OREGON': 'OR',
    'PENNSYLVANIA': 'PA',
    'PUERTO RICO': 'PR',
    'PALAU': 'PW',
    'QUEBEC (CANADA)': 'QC',
    'RHODE ISLAND': 'RI',
    'SOUTH CAROLINA': 'SC',
    'SOUTH DAKOTA': 'SD',
    'TENNESSEE': 'TN',
    'TEXAS': 'TX',
    'UNITED KINGDOM': 'UK',
    'U.S. MINOR OUTLYING ISLANDS': 'UM',
    'INVALID ENTRY (usaspending.gov error)': 'US',
    'UTAH': 'UT',
    'VIRGINIA': 'VA',
    'VIRGIN ISLANDS OF THE U.S.': 'VI',
    'VERMONT': 'VT',
    'WASHINGTON': 'WA',
    'WISCONSIN': 'WI',
    'WEST VIRGINIA': 'WV',
    'WYOMING': 'WY'
}

COUNTRIES = {
    'AFGHANISTAN': 'AFG',
    'ALBANIA': 'ALB',
    'ALGERIA': 'DZA',
    'AMERICAN SAMOA': 'ASM',
    'ANDORRA': 'AND',
    'ANGOLA': 'AGO',
    'ANGUILLA': 'AIA',
    'ANTARCTICA': 'ATA',
    'ANTIGUA AND BARBUDA': 'ATG',
    'ARGENTINA': 'ARG',
    'ARMENIA': 'ARM',
    'ARUBA': 'ABW',
    'AUSTRALIA': 'AUS',
    'AUSTRIA': 'AUT',
    'AZERBAIJAN': 'AZE',
    'BAHAMAS': 'BHS',
    'BAHRAIN': 'BHR',
    'BANGLADESH': 'BGD',
    'BARBADOS': 'BRB',
    'BELARUS': 'BLR',
    'BELGIUM': 'BEL',
    'BELIZE': 'BLZ',
    'BENIN': 'BEN',
    'BERMUDA': 'BMU',
    'BHUTAN': 'BTN',
    'BOLIVIA': 'BOL',
    'BONAIRE, SINT EUSTATIUS AND SABA': 'BES',
    'BOSNIA AND HERZEGOVINA': 'BIH',
    'BOTSWANA': 'BWA',
    'BRAZIL': 'BRA',
    'BRITISH INDIAN OCEAN TERRITORY': 'IOT',
    'BRUNEI': 'BRN',
    'BRUNEI DARUSSALAM': 'BRN',
    'BULGARIA': 'BGR',
    'BURKINA FASO': 'BFA',
    'BURUNDI': 'BDI',
    'CABO VERDE': 'CPV',
    'CAMBODIA': 'KHM',
    'CAMEROON': 'CMR',
    'CANADA': 'CAN',
    'CAYMAN ISLANDS': 'CYM',
    'CENTRAL AFRICAN REPUBLIC': 'CAF',
    'CHAD': 'TCD',
    'CHILE': 'CHL',
    'CHINA': 'CHN',
    'CHRISTMAS ISLAND': 'CXR',
    'COCOS ISLANDS': 'CCK',
    'COLOMBIA': 'COL',
    'COMOROS': 'COM',
    'CONGO': 'COG',
    'CONGO, DEMOCRATIC REPUBLIC OF THE': 'COD',
    'COOK ISLANDS': 'COK',
    'COSTA RICA': 'CRI',
    'CROATIA': 'HRV',
    'CUBA': 'CUB',
    'CURAÃ‡AO': 'CUW',
    'CURAÇAO': 'CUW',
    'CYPRUS': 'CYP',
    'CZECH REPUBLIC': 'CZE',
    'CÃ”TE D''IVOIRE': 'CIV',
    'CÔTE D''IVOIRE': 'CIV',
    'DENMARK': 'DNK',
    'DIEGO GARCIA': 'DGA',
    'DJIBOUTI': 'DJI',
    'DOMINICA': 'DMA',
    'DOMINICAN REPUBLIC': 'DOM',
    'ECUADOR': 'ECU',
    'EGYPT': 'EGY',
    'EL SALVADOR': 'SLV',
    'EQUATORIAL GUINEA': 'GNQ',
    'ERITREA': 'ERI',
    'ESTONIA': 'EST',
    'ETHIOPIA': 'ETH',
    'FALKLAND ISLANDS (MALVINAS)': 'FLK',
    'FAROE ISLANDS': 'FRO',
    'FIJI': 'FJI',
    'FINLAND': 'FIN',
    'FRANCE': 'FRA',
    'FRENCH GUIANA': 'GUF',
    'FRENCH POLYNESIA': 'PYF',
    'FRENCH SOUTHERN TERRITORIES': 'ATF',
    'GABON': 'GAB',
    'GAMBIA': 'GMB',
    'GAZA STRIP': 'XGZ',
    'GEORGIA': 'GEO',
    'GERMAN DEMOCRATIC REPUBLIC': 'DDR',
    'GERMANY': 'DEU',
    'GHANA': 'GHA',
    'GIBRALTAR': 'GIB',
    'GREECE': 'GRC',
    'GREENLAND': 'GRL',
    'GRENADA': 'GRD',
    'GUADELOUPE': 'GLP',
    'GUAM': 'GUM',
    'GUATEMALA': 'GTM',
    'GUERNSEY': 'GGY',
    'GUINEA': 'GIN',
    'GUINEA-BISSAU': 'GNB',
    'GUYANA': 'GUY',
    'HAITI': 'HTI',
    'HEARD ISLAND AND MCDONALD ISLANDS': 'HMD',
    'HOLY SEE': 'VAT',
    'HONDURAS': 'HND',
    'HONG KONG': 'HKG',
    'HUNGARY': 'HUN',
    'ICELAND': 'ISL',
    'INDIA': 'IND',
    'INDONESIA': 'IDN',
    'IRAN': 'IRN',
    'IRAN (ISLAMIC REPUBLIC OF)': 'IRN',
    'IRAQ': 'IRQ',
    'IRELAND': 'IRL',
    'ISRAEL': 'ISR',
    'ITALY': 'ITA',
    'JAMAICA': 'JAM',
    'JAPAN': 'JPN',
    'JERSEY': 'JEY',
    'JORDAN': 'JOR',
    'KAZAKHSTAN': 'KAZ',
    'KENYA': 'KEN',
    'KIRIBATI': 'KIR',
    'KOREA ( DEMOCRATIC PEOPLE''S REPUBLIC OF)': 'PRK',
    'KOREA, REPUBLIC OF': 'KOR',
    'KOSOVO': 'XKS',
    'KUWAIT': 'KWT',
    'KYRGYZSTAN': 'KGZ',
    'LAO PEOPLE''S DEMOCRATIC REPUBLIC': 'LAO',
    'LAOS': 'LAO',
    'LATVIA': 'LVA',
    'LEBANON': 'LBN',
    'LESOTHO': 'LSO',
    'LIBERIA': 'LBR',
    'LIBYA': 'LBY',
    'LIECHTENSTEIN': 'LIE',
    'LITHUANIA': 'LTU',
    'LUXEMBOURG': 'LUX',
    'MACAO': 'MAC',
    'MACEDONIA': 'MKD',
    'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF': 'MKD',
    'MADAGASCAR': 'MDG',
    'MALAWI': 'MWI',
    'MALAYSIA': 'MYS',
    'MALDIVES': 'MDV',
    'MALI': 'MLI',
    'MALTA': 'MLT',
    'MARSHALL ISLANDS': 'MHL',
    'MARTINIQUE': 'MTQ',
    'MAURITANIA': 'MRT',
    'MAURITIUS': 'MUS',
    'MAYOTTE': 'MYT',
    'MEXICO': 'MEX',
    'MICRONESIA (FEDERATED STATES OF)': 'FSM',
    'MOLDOVA': 'MDA',
    'MOLDOVA, REPUBLIC OF': 'MDA',
    'MONACO': 'MCO',
    'MONGOLIA': 'MNG',
    'MONTENEGRO': 'MNE',
    'MONTSERRAT': 'MSR',
    'MOROCCO': 'MAR',
    'MOZAMBIQUE': 'MOZ',
    'MYANMAR': 'MMR',
    'NAMIBIA': 'NAM',
    'NAURU': 'NRU',
    'NEPAL': 'NPL',
    'NETHERLANDS': 'NLD',
    'NETHERLANDS ANTILLES': 'ANT',
    'NETHERLANDS ANTILLES [NETHERLANDS]': 'ANT',
    'NEW CALEDONIA': 'NCL',
    'NEW ZEALAND': 'NZL',
    'NICARAGUA': 'NIC',
    'NIGER': 'NER',
    'NIGERIA': 'NGA',
    'NIUE': 'NIU',
    'NJUNI': 'JIB',
    'NONDISTRIBUTED': 'ZZZ',
    'NORTHERN MARIANA ISLANDS': 'MNP',
    'NORWAY': 'NOR',
    'OMAN': 'OMN',
    'PAKISTAN': 'PAK',
    'PALAU': 'PLW',
    'PANAMA': 'PAN',
    'PAPUA NEW GUINEA': 'PNG',
    'PARAGUAY': 'PRY',
    'PERU': 'PER',
    'PHILIPPINES': 'PHL',
    'POLAND': 'POL',
    'PORTUGAL': 'PRT',
    'PUERTO RICO': 'PRI',
    'QATAR': 'QAT',
    'ROMANIA': 'ROU',
    'RUSSIA': 'RUS',
    'RUSSIAN FEDERATION': 'RUS',
    'RWANDA': 'RWA',
    'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA': 'SHN',
    'SAINT KITTS AND NEVIS': 'KNA',
    'SAINT LUCIA': 'LCA',
    'SAINT PIERRE AND MIQUELON': 'SPM',
    'SAINT VINCENT AND THE GRENADINES': 'VCT',
    'SAMOA': 'WSM',
    'SAN MARINO': 'SMR',
    'SAO TOME AND PRINCIPE': 'STP',
    'SAUDI ARABIA': 'SAU',
    'SENEGAL': 'SEN',
    'SERBIA': 'SRB',
    'SERBIA AND MONTENEGRO': 'SCG',
    'SEYCHELLES': 'SYC',
    'SIERRA LEONE': 'SLE',
    'SINGAPORE': 'SGP',
    'SLOVAKIA': 'SVK',
    'SLOVENIA': 'SVN',
    'SOLOMON ISLANDS': 'SLB',
    'SOMALIA': 'SOM',
    'SOUTH AFRICA': 'ZAF',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'SGS',
    'SOUTH KOREA': 'KOR',
    'SOUTH SUDAN': 'SSD',
    'SPAIN': 'ESP',
    'SPRATLY ISLANDS': 'XSP',
    'SRI LANKA': 'LKA',
    'SUDAN': 'SDN',
    'SURINAME': 'SUR',
    'SVALBARD': 'XSV',
    'SWAZILAND': 'SWZ',
    'SWEDEN': 'SWE',
    'SWITZERLAND': 'CHE',
    'SYRIA': 'SYR',
    'TAIWAN, PROVINCE OF CHINA': 'TWN',
    'TAJIKISTAN': 'TJK',
    'TANZANIA': 'TZA',
    'TANZANIA, UNITED REPUBLIC OF': 'TZA',
    'THAILAND': 'THA',
    'TIMOR-LESTE': 'TLS',
    'TOGO': 'TGO',
    'TONGA': 'TON',
    'TRINIDAD AND TOBAGO': 'TTO',
    'TUNISIA': 'TUN',
    'TURKEY': 'TUR',
    'TURKMENISTAN': 'TKM',
    'TURKS AND CAICOS ISLANDS': 'TCA',
    'TUVALU': 'TUV',
    'UGANDA': 'UGA',
    'UKRAINE': 'UKR',
    'UNITED ARAB EMIRATES': 'ARE',
    'UNITED KINGDOM': 'GBR',
    'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN': 'GBR',
    'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN  IRELAND': 'GBR',
    'UNITED STATES': 'USA',
    'UNITED STATES MINOR OUTLYING ISLANDS': 'UMI',
    'UNITED STATES OF AMERICA': 'USA',
    'URUGUAY': 'URY',
    'UZBEKISTAN': 'UZB',
    'VANUATU': 'VUT',
    'VENEZUELA': 'VEN',
    'VENEZUELA (BOLIVARIAN REPUBLIC OF)': 'VEN',
    'VIET NAM': 'VNM',
    'VIETNAM': 'VNM',
    'VIRGIN ISLANDS (BRITISH)': 'VGB',
    'VIRGIN ISLANDS (U.S.)': 'VIR',
    'WEST BANK': 'XWB',
    'WESTERN SAHARA *': 'ESH',
    'YEMEN': 'YEM',
    'YUGOSLAVIA': 'YUG',
    'ZAMBIA': 'ZMB',
    'ZIMBABWE': 'ZWE'
}

OLD_FIELDS = [
    'unique_transaction_id',
    'last_modified_date',
    'transaction_status',
    'dollarsobligated',
    'baseandexercisedoptionsvalue',
    'baseandalloptionsvalue',
    'maj_agency_cat',
    'mod_agency',
    'maj_fund_agency_cat',
    'contractingofficeagencyid',
    'contractingofficeid',
    'fundingrequestingagencyid',
    'fundingrequestingofficeid',
    'fundedbyforeignentity',
    'signeddate',
    'effectivedate',
    'currentcompletiondate',
    'ultimatecompletiondate',
    'lastdatetoorder',
    'contractactiontype',
    'reasonformodification',
    'typeofcontractpricing',
    'priceevaluationpercentdifference',
    'subcontractplan',
    'lettercontract',
    'multiyearcontract',
    'performancebasedservicecontract',
    'majorprogramcode',
    'contingencyhumanitarianpeacekeepingoperation',
    'contractfinancing',
    'costorpricingdata',
    'costaccountingstandardsclause',
    'descriptionofcontractrequirement',
    'purchasecardaspaymentmethod',
    'numberofactions',
    'nationalinterestactioncode',
    'progsourceagency',
    'progsourceaccount',
    'progsourcesubacct',
    'account_title',
    'rec_flag',
    'typeofidc',
    'multipleorsingleawardidc',
    'programacronym',
    'vendorname',
    'vendoralternatename',
    'vendorlegalorganizationname',
    'vendordoingasbusinessname',
    'divisionname',
    'divisionnumberorofficecode',
    'vendorenabled',
    'vendorlocationdisableflag',
    'ccrexception',
    'streetaddress',
    'streetaddress2',
    'streetaddress3',
    'city',
    'state',
    'zipcode',
    'vendorcountrycode',
    'vendor_state_code',
    'vendor_cd',
    'congressionaldistrict',
    'vendorsitecode',
    'vendoralternatesitecode',
    'dunsnumber',
    'parentdunsnumber',
    'phoneno',
    'faxno',
    'registrationdate',
    'renewaldate',
    'mod_parent',
    'locationcode',
    'statecode',
    'PlaceofPerformanceCity',
    'pop_state_code',
    'placeofperformancecountrycode',
    'placeofperformancezipcode',
    'pop_cd',
    'placeofperformancecongressionaldistrict',
    'psc_cat',
    'productorservicecode',
    'systemequipmentcode',
    'claimantprogramcode',
    'principalnaicscode',
    'informationtechnologycommercialitemcategory',
    'gfe_gfp',
    'useofepadesignatedproducts',
    'recoveredmaterialclauses',
    'seatransportation',
    'contractbundling',
    'consolidatedcontract',
    'countryoforigin',
    'placeofmanufacture',
    'manufacturingorganizationtype',
    'agencyid',
    'piid',
    'modnumber',
    'transactionnumber',
    'fiscal_year',
    'idvagencyid',
    'idvpiid',
    'idvmodificationnumber',
    'solicitationid',
    'extentcompeted',
    'reasonnotcompeted',
    'numberofoffersreceived',
    'commercialitemacquisitionprocedures',
    'commercialitemtestprogram',
    'smallbusinesscompetitivenessdemonstrationprogram',
    'a76action',
    'competitiveprocedures',
    'solicitationprocedures',
    'typeofsetaside',
    'localareasetaside',
    'evaluatedpreference',
    'fedbizopps',
    'research',
    'statutoryexceptiontofairopportunity',
    'organizationaltype',
    'numberofemployees',
    'annualrevenue',
    'firm8aflag',
    'hubzoneflag',
    'sdbflag',
    'issbacertifiedsmalldisadvantagedbusiness',
    'shelteredworkshopflag',
    'hbcuflag',
    'educationalinstitutionflag',
    'womenownedflag',
    'veteranownedflag',
    'srdvobflag',
    'localgovernmentflag',
    'minorityinstitutionflag',
    'aiobflag',
    'stategovernmentflag',
    'federalgovernmentflag',
    'minorityownedbusinessflag',
    'apaobflag',
    'tribalgovernmentflag',
    'baobflag',
    'naobflag',
    'saaobflag',
    'nonprofitorganizationflag',
    'isothernotforprofitorganization',
    'isforprofitorganization',
    'isfoundation',
    'haobflag',
    'ishispanicservicinginstitution',
    'emergingsmallbusinessflag',
    'hospitalflag',
    'contractingofficerbusinesssizedetermination',
    'is1862landgrantcollege',
    'is1890landgrantcollege',
    'is1994landgrantcollege',
    'isveterinarycollege',
    'isveterinaryhospital',
    'isprivateuniversityorcollege',
    'isschoolofforestry',
    'isstatecontrolledinstitutionofhigherlearning',
    'isserviceprovider',
    'receivescontracts',
    'receivesgrants',
    'receivescontractsandgrants',
    'isairportauthority',
    'iscouncilofgovernments',
    'ishousingauthoritiespublicortribal',
    'isinterstateentity',
    'isplanningcommission',
    'isportauthority',
    'istransitauthority',
    'issubchapterscorporation',
    'islimitedliabilitycorporation',
    'isforeignownedandlocated',
    'isarchitectureandengineering',
    'isdotcertifieddisadvantagedbusinessenterprise',
    'iscitylocalgovernment',
    'iscommunitydevelopedcorporationownedfirm',
    'iscommunitydevelopmentcorporation',
    'isconstructionfirm',
    'ismanufacturerofgoods',
    'iscorporateentitynottaxexempt',
    'iscountylocalgovernment',
    'isdomesticshelter',
    'isfederalgovernmentagency',
    'isfederallyfundedresearchanddevelopmentcorp',
    'isforeigngovernment',
    'isindiantribe',
    'isintermunicipallocalgovernment',
    'isinternationalorganization',
    'islaborsurplusareafirm',
    'islocalgovernmentowned',
    'ismunicipalitylocalgovernment',
    'isnativehawaiianownedorganizationorfirm',
    'isotherbusinessororganization',
    'isotherminorityowned',
    'ispartnershiporlimitedliabilitypartnership',
    'isschooldistrictlocalgovernment',
    'issmallagriculturalcooperative',
    'issoleproprietorship',
    'istownshiplocalgovernment',
    'istriballyownedfirm',
    'istribalcollege',
    'isalaskannativeownedcorporationorfirm',
    'iscorporateentitytaxexempt',
    'iswomenownedsmallbusiness',
    'isecondisadvwomenownedsmallbusiness',
    'isjointventurewomenownedsmallbusiness',
    'isjointventureecondisadvwomenownedsmallbusiness',
    'walshhealyact',
    'servicecontractact',
    'davisbaconact',
    'clingercohenact',
    'otherstatutoryauthority',
    'prime_awardee_executive1',
    'prime_awardee_executive1_compensation',
    'prime_awardee_executive2',
    'prime_awardee_executive2_compensation',
    'prime_awardee_executive3',
    'prime_awardee_executive3_compensation',
    'prime_awardee_executive4',
    'prime_awardee_executive4_compensation',
    'prime_awardee_executive5',
    'prime_awardee_executive5_compensation',
    'interagencycontractingauthority',
]

NEW_FIELDS = [
    'unique_transaction_id',
    'last_modified_date',
    'transaction_status',
    'dollars_obligated',
    'base_and_exercised_options_value',
    'base_and_all_options_value',
    'contracting_department_id',
    'contracting_department_name',
    'contracting_agency_id',
    'contracting_agency_name',
    'contracting_agency_id_redundant',
    'contracting_agency_name_redundant',
    'contracting_office_id',
    'contracting_office_name',
    'funding_department_id',
    'funding_department_name',
    'funding_agency_id',
    'funding_agency_name',
    'funding_office_id',
    'funding_office_name',
    'funded_by_foreign_entity',
    'signed_date',
    'effective_date',
    'current_completion_date',
    'ultimate_completion_date',
    'last_date_to_order',
    'contract_action_type',
    'reason_for_modification',
    'type_of_contract_pricing',
    'price_evaluation_percent_difference',
    'subcontract_plan',
    'letter_contract',
    'multiyear_contract',
    'performance_based_service_contract',
    'major_program_code',
    'contingency_humanitarian_peacekeeping_operation',
    'contract_financing',
    'cost_or_pricing_data',
    'cost_accounting_standards_clause',
    'descriptionofcontractrequirement',
    'purchase_card_as_payment_method',
    'number_of_actions',
    'national_interest_action',
    'prog_source_agency',
    'prog_source_account',
    'prog_source_subacct',
    'account_title',
    'recovery_flag',
    'type_of_idc',
    'multiple_or_single_award_idc',
    'program_acronym',
    'contractor_name',
    'contractor_alternate_name',
    'contractor_legal_organization_name',
    'contractor_doing_as_business_name',
    'contractor_division_name',
    'contractor_division_number_or_office_code',
    'contractor_enabled',
    'contractor_location_disable_flag',
    'contractor_ccr_exception',
    'contractor_street_address_1',
    'contractor_street_address_2',
    'contractor_street_address_3',
    'contractor_city',
    'contractor_state',
    'contractor_state_redundant',
    'contractor_zip_code',
    'contractor_country',
    'contractor_congressional_district',
    'contractor_congressional_district_redundant',
    'contractor_site_code',
    'contractor_alternate_site_code',
    'contractor_duns_number',
    'contractor_parent_duns_number',
    'contractor_phone_number',
    'contractor_fax_number',
    'contractor_registration_date',
    'contractor_renewal_date',
    'contractor_parent_name',
    'location_code',
    'place_of_performance_city',
    'place_of_performance_state',
    'place_of_performance_state_redundant',
    'place_of_performance_country',
    'place_of_performance_zip_code',
    'place_of_performance_congressional_district',
    'place_of_performance_congressional_district_redundant',
    'product_or_service_category',
    'product_or_service_code',
    'system_or_equipment_code',
    'system_or_equipment_description',
    'claimant_program',
    'naics',
    'information_technology_commercial_item_category',
    'gfe_gfp',
    'use_of_epa_designated_products',
    'recovered_material_clauses',
    'sea_transportation',
    'contract_bundling',
    'consolidated_contract',
    'country_of_origin',
    'place_of_manufacture',
    'manufacturing_organization_type',
    'agency_id',
    'agency_name',
    'piid',
    'modification_number',
    'transaction_number',
    'fiscal_year',
    'idv_agency_id',
    'idv_piid',
    'idv_modification_number',
    'solicitation_id',
    'extent_competed',
    'reason_not_competed',
    'number_of_offers_received',
    'commercial_item_acquisition_procedures',
    'commercial_item_test_program',
    'small_business_competitiveness_demonstration_program',
    'a76action',
    'competitive_procedures',
    'solicitation_procedures',
    'type_of_set_aside',
    'local_area_set_aside',
    'evaluated_preference',
    'fedbizopps',
    'research',
    'statutory_exception_to_fair_opportunity',
    'contractor_organizational_type',
    'contractor_number_of_employees',
    'contractor_annual_revenue',
    'firm8aflag',
    'hubzoneflag',
    'sdbflag',
    'issbacertifiedsmalldisadvantagedbusiness',
    'shelteredworkshopflag',
    'hbcuflag',
    'educationalinstitutionflag',
    'womenownedflag',
    'veteranownedflag',
    'srdvobflag',
    'localgovernmentflag',
    'minorityinstitutionflag',
    'aiobflag',
    'stategovernmentflag',
    'federalgovernmentflag',
    'minorityownedbusinessflag',
    'apaobflag',
    'tribalgovernmentflag',
    'baobflag',
    'naobflag',
    'saaobflag',
    'nonprofitorganizationflag',
    'isothernotforprofitorganization',
    'isforprofitorganization',
    'isfoundation',
    'haobflag',
    'ishispanicservicinginstitution',
    'emergingsmallbusinessflag',
    'hospitalflag',
    'contractingofficerbusinesssizedetermination',
    'is1862landgrantcollege',
    'is1890landgrantcollege',
    'is1994landgrantcollege',
    'isveterinarycollege',
    'isveterinaryhospital',
    'isprivateuniversityorcollege',
    'isschoolofforestry',
    'isstatecontrolledinstitutionofhigherlearning',
    'isserviceprovider',
    'receivescontracts',
    'receivesgrants',
    'receivescontractsandgrants',
    'isairportauthority',
    'iscouncilofgovernments',
    'ishousingauthoritiespublicortribal',
    'isinterstateentity',
    'isplanningcommission',
    'isportauthority',
    'istransitauthority',
    'issubchapterscorporation',
    'islimitedliabilitycorporation',
    'isforeignownedandlocated',
    'isarchitectureandengineering',
    'isdotcertifieddisadvantagedbusinessenterprise',
    'iscitylocalgovernment',
    'iscommunitydevelopedcorporationownedfirm',
    'iscommunitydevelopmentcorporation',
    'isconstructionfirm',
    'ismanufacturerofgoods',
    'iscorporateentitynottaxexempt',
    'iscountylocalgovernment',
    'isdomesticshelter',
    'isfederalgovernmentagency',
    'isfederallyfundedresearchanddevelopmentcorp',
    'isforeigngovernment',
    'isindiantribe',
    'isintermunicipallocalgovernment',
    'isinternationalorganization',
    'islaborsurplusareafirm',
    'islocalgovernmentowned',
    'ismunicipalitylocalgovernment',
    'isnativehawaiianownedorganizationorfirm',
    'isotherbusinessororganization',
    'isotherminorityowned',
    'ispartnershiporlimitedliabilitypartnership',
    'isschooldistrictlocalgovernment',
    'issmallagriculturalcooperative',
    'issoleproprietorship',
    'istownshiplocalgovernment',
    'istriballyownedfirm',
    'istribalcollege',
    'isalaskannativeownedcorporationorfirm',
    'iscorporateentitytaxexempt',
    'iswomenownedsmallbusiness',
    'isecondisadvwomenownedsmallbusiness',
    'isjointventurewomenownedsmallbusiness',
    'isjointventureecondisadvwomenownedsmallbusiness',
    'walsh_healy_act',
    'service_contract_act',
    'davis_bacon_act',
    'clinger_cohen_act',
    'other_statutory_authority',
    'prime_awardee_executive1',
    'prime_awardee_executive1_compensation',
    'prime_awardee_executive2',
    'prime_awardee_executive2_compensation',
    'prime_awardee_executive3',
    'prime_awardee_executive3_compensation',
    'prime_awardee_executive4',
    'prime_awardee_executive4_compensation',
    'prime_awardee_executive5',
    'prime_awardee_executive5_compensation',
    'interagency_contracting_authority'
]
