CREATE OR REPLACE FUNCTION generate_contract_all()
  RETURNS VOID AS $$
BEGIN
  INSERT INTO contract_all
    SELECT
      unique_transaction_id,
      validate_date(last_modified_date),
      transaction_status,
      cast(dollarsobligated AS MONEY),
      cast(baseandexercisedoptionsvalue AS MONEY),
      cast(baseandalloptionsvalue AS MONEY),
      left_text(maj_agency_cat), -- contracting_department_id
      right_text(maj_agency_cat), -- contracting_department_name
      left_text(contractingofficeagencyid), -- contracting_agency_id
      right_text(contractingofficeagencyid), -- contracting_agency_name
      left_text(contractingofficeid), -- contracting_office_id
      right_text(contractingofficeid), -- contracting_office_name
      left_text(maj_fund_agency_cat), -- funding_department_id
      right_text(maj_fund_agency_cat), -- funding_department_name
      left_text(fundingrequestingagencyid), -- funding_agency_id
      right_text(fundingrequestingagencyid), -- funding_agency_name
      left_text(fundingrequestingofficeid), -- funding_office_id
      right_text(fundingrequestingofficeid), -- funding_office_name
      funded_by_foreign_entity(fundedbyforeignentity),
      validate_date(signeddate),
      validate_date(effectivedate),
      validate_date(currentcompletiondate),
      validate_date(ultimatecompletiondate),
      validate_date(lastdatetoorder),
      contract_action_type(contractactiontype),
      NULLIF(left_text(reasonformodification), ''),
      type_of_contract_pricing(typeofcontractpricing),
      cast(priceevaluationpercentdifference as real),
      NULLIF(left_text(subcontractplan), ''),
      NULLIF(left_text(lettercontract), ''),
      NULLIF(left_text(multiyearcontract), ''),
      performance_based_service_contract(performancebasedservicecontract),
      majorprogramcode,
      NULLIF(left_text(contingencyhumanitarianpeacekeepingoperation), ''),
      NULLIF(left_text(contractfinancing), ''),
      NULLIF(left_text(costorpricingdata), ''),
      costaccountingstandardsclause,
      descriptionofcontractrequirement,
      NULLIF(left_text(purchasecardaspaymentmethod), ''),
      CAST(numberofactions as INTEGER),
      national_interest_action(nationalinterestactioncode),
      progsourceagency,
      progsourceaccount,
      progsourcesubacct,
      account_title,
      rec_flag,
      type_of_idc(typeofidc),
      NULLIF(left_text(multipleorsingleawardidc), ''),
      programacronym,
      vendorname,
      vendoralternatename,
      vendorlegalorganizationname,
      vendordoingasbusinessname,
      divisionname,
      divisionnumberorofficecode,
      vendorenabled,
      vendorlocationdisableflag,
      ccr_exception(ccrexception),
      streetaddress,
      streetaddress2,
      streetaddress3,
      city,
      state,
      zipcode,
      validate_country(vendorcountrycode),
      congressionaldistrict,
      vendorsitecode,
      vendoralternatesitecode,
      dunsnumber,
      parentdunsnumber,
      phoneno,
      faxno,
      validate_date(registrationdate),
      validate_date(renewaldate),
      mod_parent,
      --
      --
      --
      locationcode,
      PlaceofPerformanceCity,
      validate_state(pop_state_code),
      validate_country(placeofperformancecountrycode),
      placeofperformancezipcode,
      placeofperformancecongressionaldistrict,
      psc_cat,
      NULLIF(left_text(productorservicecode), ''),
      NULLIF(trim(BOTH FROM systemequipmentcode), ''),
      NULLIF(trim(BOTH FROM claimantprogramcode), ''),
      NULLIF(trim(BOTH FROM principalnaicscode), ''),
      NULLIF(trim(BOTH FROM informationtechnologycommercialitemcategory), ''),
      NULLIF(trim(BOTH FROM gfe_gfp), ''),
      NULLIF(trim(BOTH FROM useofepadesignatedproducts), ''),
      NULLIF(trim(BOTH FROM recoveredmaterialclauses), ''),
      NULLIF(trim(BOTH FROM seatransportation), ''),
      NULLIF(trim(BOTH FROM contractbundling), ''),
      NULLIF(trim(BOTH FROM consolidatedcontract), ''),
      NULLIF(trim(BOTH FROM countryoforigin), ''),
      NULLIF(trim(BOTH FROM placeofmanufacture), ''),
      NULLIF(trim(BOTH FROM manufacturingorganizationtype), ''),
      NULLIF(trim(BOTH FROM agencyid), ''),
      NULLIF(trim(BOTH FROM piid), ''),
      NULLIF(trim(BOTH FROM modnumber), ''),
      NULLIF(trim(BOTH FROM transactionnumber), ''),
      NULLIF(trim(BOTH FROM fiscal_year), ''),
      NULLIF(trim(BOTH FROM idvagencyid), ''),
      NULLIF(trim(BOTH FROM idvpiid), ''),
      NULLIF(trim(BOTH FROM idvmodificationnumber), ''),
      NULLIF(trim(BOTH FROM solicitationid), ''),
      NULLIF(trim(BOTH FROM extentcompeted), ''),
      NULLIF(trim(BOTH FROM reasonnotcompeted), ''),
      NULLIF(trim(BOTH FROM numberofoffersreceived), ''),
      NULLIF(trim(BOTH FROM commercialitemacquisitionprocedures), ''),
      NULLIF(trim(BOTH FROM commercialitemtestprogram), ''),
      NULLIF(trim(BOTH FROM smallbusinesscompetitivenessdemonstrationprogram), ''),
      NULLIF(trim(BOTH FROM a76action), ''),
      NULLIF(trim(BOTH FROM competitiveprocedures), ''),
      NULLIF(trim(BOTH FROM solicitationprocedures), ''),
      NULLIF(trim(BOTH FROM typeofsetaside), ''),
      NULLIF(trim(BOTH FROM localareasetaside), ''),
      NULLIF(trim(BOTH FROM evaluatedpreference), ''),
      NULLIF(trim(BOTH FROM fedbizopps), ''),
      NULLIF(trim(BOTH FROM research), ''),
      NULLIF(trim(BOTH FROM statutoryexceptiontofairopportunity), ''),
      NULLIF(trim(BOTH FROM organizationaltype), ''),
      NULLIF(trim(BOTH FROM numberofemployees), ''),
      NULLIF(trim(BOTH FROM annualrevenue), ''),
      NULLIF(trim(BOTH FROM firm8aflag), ''),
      NULLIF(trim(BOTH FROM hubzoneflag), ''),
      NULLIF(trim(BOTH FROM sdbflag), ''),
      NULLIF(trim(BOTH FROM issbacertifiedsmalldisadvantagedbusiness), ''),
      NULLIF(trim(BOTH FROM shelteredworkshopflag), ''),
      NULLIF(trim(BOTH FROM hbcuflag), ''),
      NULLIF(trim(BOTH FROM educationalinstitutionflag), ''),
      NULLIF(trim(BOTH FROM womenownedflag), ''),
      NULLIF(trim(BOTH FROM veteranownedflag), ''),
      NULLIF(trim(BOTH FROM srdvobflag), ''),
      NULLIF(trim(BOTH FROM localgovernmentflag), ''),
      NULLIF(trim(BOTH FROM minorityinstitutionflag), ''),
      NULLIF(trim(BOTH FROM aiobflag), ''),
      NULLIF(trim(BOTH FROM stategovernmentflag), ''),
      NULLIF(trim(BOTH FROM federalgovernmentflag), ''),
      NULLIF(trim(BOTH FROM minorityownedbusinessflag), ''),
      NULLIF(trim(BOTH FROM apaobflag), ''),
      NULLIF(trim(BOTH FROM tribalgovernmentflag), ''),
      NULLIF(trim(BOTH FROM baobflag), ''),
      NULLIF(trim(BOTH FROM naobflag), ''),
      NULLIF(trim(BOTH FROM saaobflag), ''),
      NULLIF(trim(BOTH FROM nonprofitorganizationflag), ''),
      NULLIF(trim(BOTH FROM isothernotforprofitorganization), ''),
      NULLIF(trim(BOTH FROM isforprofitorganization), ''),
      NULLIF(trim(BOTH FROM isfoundation), ''),
      NULLIF(trim(BOTH FROM haobflag), ''),
      NULLIF(trim(BOTH FROM ishispanicservicinginstitution), ''),
      NULLIF(trim(BOTH FROM emergingsmallbusinessflag), ''),
      NULLIF(trim(BOTH FROM hospitalflag), ''),
      NULLIF(trim(BOTH FROM contractingofficerbusinesssizedetermination), ''),
      NULLIF(trim(BOTH FROM is1862landgrantcollege), ''),
      NULLIF(trim(BOTH FROM is1890landgrantcollege), ''),
      NULLIF(trim(BOTH FROM is1994landgrantcollege), ''),
      NULLIF(trim(BOTH FROM isveterinarycollege), ''),
      NULLIF(trim(BOTH FROM isveterinaryhospital), ''),
      NULLIF(trim(BOTH FROM isprivateuniversityorcollege), ''),
      NULLIF(trim(BOTH FROM isschoolofforestry), ''),
      NULLIF(trim(BOTH FROM isstatecontrolledinstitutionofhigherlearning), ''),
      NULLIF(trim(BOTH FROM isserviceprovider), ''),
      NULLIF(trim(BOTH FROM receivescontracts), ''),
      NULLIF(trim(BOTH FROM receivesgrants), ''),
      NULLIF(trim(BOTH FROM receivescontractsandgrants), ''),
      NULLIF(trim(BOTH FROM isairportauthority), ''),
      NULLIF(trim(BOTH FROM iscouncilofgovernments), ''),
      NULLIF(trim(BOTH FROM ishousingauthoritiespublicortribal), ''),
      NULLIF(trim(BOTH FROM isinterstateentity), ''),
      NULLIF(trim(BOTH FROM isplanningcommission), ''),
      NULLIF(trim(BOTH FROM isportauthority), ''),
      NULLIF(trim(BOTH FROM istransitauthority), ''),
      NULLIF(trim(BOTH FROM issubchapterscorporation), ''),
      NULLIF(trim(BOTH FROM islimitedliabilitycorporation), ''),
      NULLIF(trim(BOTH FROM isforeignownedandlocated), ''),
      NULLIF(trim(BOTH FROM isarchitectureandengineering), ''),
      NULLIF(trim(BOTH FROM isdotcertifieddisadvantagedbusinessenterprise), ''),
      NULLIF(trim(BOTH FROM iscitylocalgovernment), ''),
      NULLIF(trim(BOTH FROM iscommunitydevelopedcorporationownedfirm), ''),
      NULLIF(trim(BOTH FROM iscommunitydevelopmentcorporation), ''),
      NULLIF(trim(BOTH FROM isconstructionfirm), ''),
      NULLIF(trim(BOTH FROM ismanufacturerofgoods), ''),
      NULLIF(trim(BOTH FROM iscorporateentitynottaxexempt), ''),
      NULLIF(trim(BOTH FROM iscountylocalgovernment), ''),
      NULLIF(trim(BOTH FROM isdomesticshelter), ''),
      NULLIF(trim(BOTH FROM isfederalgovernmentagency), ''),
      NULLIF(trim(BOTH FROM isfederallyfundedresearchanddevelopmentcorp), ''),
      NULLIF(trim(BOTH FROM isforeigngovernment), ''),
      NULLIF(trim(BOTH FROM isindiantribe), ''),
      NULLIF(trim(BOTH FROM isintermunicipallocalgovernment), ''),
      NULLIF(trim(BOTH FROM isinternationalorganization), ''),
      NULLIF(trim(BOTH FROM islaborsurplusareafirm), ''),
      NULLIF(trim(BOTH FROM islocalgovernmentowned), ''),
      NULLIF(trim(BOTH FROM ismunicipalitylocalgovernment), ''),
      NULLIF(trim(BOTH FROM isnativehawaiianownedorganizationorfirm), ''),
      NULLIF(trim(BOTH FROM isotherbusinessororganization), ''),
      NULLIF(trim(BOTH FROM isotherminorityowned), ''),
      NULLIF(trim(BOTH FROM ispartnershiporlimitedliabilitypartnership), ''),
      NULLIF(trim(BOTH FROM isschooldistrictlocalgovernment), ''),
      NULLIF(trim(BOTH FROM issmallagriculturalcooperative), ''),
      NULLIF(trim(BOTH FROM issoleproprietorship), ''),
      NULLIF(trim(BOTH FROM istownshiplocalgovernment), ''),
      NULLIF(trim(BOTH FROM istriballyownedfirm), ''),
      NULLIF(trim(BOTH FROM istribalcollege), ''),
      NULLIF(trim(BOTH FROM isalaskannativeownedcorporationorfirm), ''),
      NULLIF(trim(BOTH FROM iscorporateentitytaxexempt), ''),
      NULLIF(trim(BOTH FROM iswomenownedsmallbusiness), ''),
      NULLIF(trim(BOTH FROM isecondisadvwomenownedsmallbusiness), ''),
      NULLIF(trim(BOTH FROM isjointventurewomenownedsmallbusiness), ''),
      NULLIF(trim(BOTH FROM isjointventureecondisadvwomenownedsmallbusiness), ''),
      NULLIF(trim(BOTH FROM walshhealyact), ''),
      NULLIF(trim(BOTH FROM servicecontractact), ''),
      NULLIF(trim(BOTH FROM davisbaconact), ''),
      NULLIF(trim(BOTH FROM clingercohenact), ''),
      NULLIF(trim(BOTH FROM otherstatutoryauthority), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive1), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive1_compensation), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive2), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive2_compensation), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive3), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive3_compensation), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive4), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive4_compensation), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive5), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive5_compensation), ''),
      NULLIF(trim(BOTH FROM interagencycontractingauthority), '')
    FROM contract_csv
   ON CONFLICT (unique_transaction_id, last_modified_date)
    DO NOTHING;
END
$$ LANGUAGE plpgsql;