CREATE OR REPLACE FUNCTION import_contract_csv(file TEXT)
  RETURNS VOID AS $$
BEGIN
  TRUNCATE temp_contract;

  EXECUTE format('COPY temp_contract FROM ''%s'' WITH CSV HEADER DELIMITER AS '',''', file);

  INSERT INTO contract_csv
    SELECT
      NULLIF(trim(BOTH FROM unique_transaction_id), ''),
      NULLIF(trim(BOTH FROM transaction_status), ''),
      NULLIF(trim(BOTH FROM dollarsobligated), ''),
      NULLIF(trim(BOTH FROM baseandexercisedoptionsvalue), ''),
      NULLIF(trim(BOTH FROM baseandalloptionsvalue), ''),
      NULLIF(trim(BOTH FROM maj_agency_cat), ''),
      NULLIF(trim(BOTH FROM mod_agency), ''),
      NULLIF(trim(BOTH FROM maj_fund_agency_cat), ''),
      NULLIF(trim(BOTH FROM contractingofficeagencyid), ''),
      NULLIF(trim(BOTH FROM contractingofficeid), ''),
      NULLIF(trim(BOTH FROM fundingrequestingagencyid), ''),
      NULLIF(trim(BOTH FROM fundingrequestingofficeid), ''),
      NULLIF(trim(BOTH FROM fundedbyforeignentity), ''),
      NULLIF(trim(BOTH FROM signeddate), ''),
      NULLIF(trim(BOTH FROM effectivedate), ''),
      NULLIF(trim(BOTH FROM currentcompletiondate), ''),
      NULLIF(trim(BOTH FROM ultimatecompletiondate), ''),
      NULLIF(trim(BOTH FROM lastdatetoorder), ''),
      NULLIF(trim(BOTH FROM contractactiontype), ''),
      NULLIF(trim(BOTH FROM reasonformodification), ''),
      NULLIF(trim(BOTH FROM typeofcontractpricing), ''),
      NULLIF(trim(BOTH FROM priceevaluationpercentdifference), ''),
      NULLIF(trim(BOTH FROM subcontractplan), ''),
      NULLIF(trim(BOTH FROM lettercontract), ''),
      NULLIF(trim(BOTH FROM multiyearcontract), ''),
      NULLIF(trim(BOTH FROM performancebasedservicecontract), ''),
      NULLIF(trim(BOTH FROM majorprogramcode), ''),
      NULLIF(trim(BOTH FROM contingencyhumanitarianpeacekeepingoperation), ''),
      NULLIF(trim(BOTH FROM contractfinancing), ''),
      NULLIF(trim(BOTH FROM costorpricingdata), ''),
      NULLIF(trim(BOTH FROM costaccountingstandardsclause), ''),
      NULLIF(trim(BOTH FROM descriptionofcontractrequirement), ''),
      NULLIF(trim(BOTH FROM purchasecardaspaymentmethod), ''),
      NULLIF(trim(BOTH FROM numberofactions), ''),
      NULLIF(trim(BOTH FROM nationalinterestactioncode), ''),
      NULLIF(trim(BOTH FROM progsourceagency), ''),
      NULLIF(trim(BOTH FROM progsourceaccount), ''),
      NULLIF(trim(BOTH FROM progsourcesubacct), ''),
      NULLIF(trim(BOTH FROM account_title), ''),
      NULLIF(trim(BOTH FROM rec_flag), ''),
      NULLIF(trim(BOTH FROM typeofidc), ''),
      NULLIF(trim(BOTH FROM multipleorsingleawardidc), ''),
      NULLIF(trim(BOTH FROM programacronym), ''),
      NULLIF(trim(BOTH FROM vendorname), ''),
      NULLIF(trim(BOTH FROM vendoralternatename), ''),
      NULLIF(trim(BOTH FROM vendorlegalorganizationname), ''),
      NULLIF(trim(BOTH FROM vendordoingasbusinessname), ''),
      NULLIF(trim(BOTH FROM divisionname), ''),
      NULLIF(trim(BOTH FROM divisionnumberorofficecode), ''),
      NULLIF(trim(BOTH FROM vendorenabled), ''),
      NULLIF(trim(BOTH FROM vendorlocationdisableflag), ''),
      NULLIF(trim(BOTH FROM ccrexception), ''),
      NULLIF(trim(BOTH FROM streetaddress), ''),
      NULLIF(trim(BOTH FROM streetaddress2), ''),
      NULLIF(trim(BOTH FROM streetaddress3), ''),
      NULLIF(trim(BOTH FROM city), ''),
      NULLIF(trim(BOTH FROM state), ''),
      NULLIF(trim(BOTH FROM zipcode), ''),
      NULLIF(trim(BOTH FROM vendorcountrycode), ''),
      NULLIF(trim(BOTH FROM vendor_state_code), ''),
      NULLIF(trim(BOTH FROM vendor_cd), ''),
      NULLIF(trim(BOTH FROM congressionaldistrict), ''),
      NULLIF(trim(BOTH FROM vendorsitecode), ''),
      NULLIF(trim(BOTH FROM vendoralternatesitecode), ''),
      NULLIF(trim(BOTH FROM dunsnumber), ''),
      NULLIF(trim(BOTH FROM parentdunsnumber), ''),
      NULLIF(trim(BOTH FROM phoneno), ''),
      NULLIF(trim(BOTH FROM faxno), ''),
      NULLIF(trim(BOTH FROM registrationdate), ''),
      NULLIF(trim(BOTH FROM renewaldate), ''),
      NULLIF(trim(BOTH FROM mod_parent), ''),
      NULLIF(trim(BOTH FROM locationcode), ''),
      NULLIF(trim(BOTH FROM statecode), ''),
      NULLIF(trim(BOTH FROM PlaceofPerformanceCity), ''),
      NULLIF(trim(BOTH FROM pop_state_code), ''),
      NULLIF(trim(BOTH FROM placeofperformancecountrycode), ''),
      NULLIF(trim(BOTH FROM placeofperformancezipcode), ''),
      NULLIF(trim(BOTH FROM pop_cd), ''),
      NULLIF(trim(BOTH FROM placeofperformancecongressionaldistrict), ''),
      NULLIF(trim(BOTH FROM psc_cat), ''),
      NULLIF(trim(BOTH FROM productorservicecode), ''),
      NULLIF(trim(BOTH FROM systemequipmentcode), ''),
      NULLIF(trim(BOTH FROM claimantprogramcode), ''),
      NULLIF(trim(BOTH FROM principalnaicscode), ''),
      NULLIF(trim(BOTH FROM informationtechnologycommercialitemcategory), ''),
      NULLIF(trim(BOTH FROM gfe_gfp), ''),
      NULLIF(trim(BOTH FROM useofepadesignatedproducts), ''),
      NULLIF(trim(BOTH FROM recoveredmaterialclauses), ''),
      NULLIF(trim(BOTH FROM seatransportation), ''),
      NULLIF(trim(BOTH FROM contractbundling), ''),
      NULLIF(trim(BOTH FROM consolidatedcontract), ''),
      NULLIF(trim(BOTH FROM countryoforigin), ''),
      NULLIF(trim(BOTH FROM placeofmanufacture), ''),
      NULLIF(trim(BOTH FROM manufacturingorganizationtype), ''),
      NULLIF(trim(BOTH FROM agencyid), ''),
      NULLIF(trim(BOTH FROM piid), ''),
      NULLIF(trim(BOTH FROM modnumber), ''),
      NULLIF(trim(BOTH FROM transactionnumber), ''),
      NULLIF(trim(BOTH FROM fiscal_year), ''),
      NULLIF(trim(BOTH FROM idvagencyid), ''),
      NULLIF(trim(BOTH FROM idvpiid), ''),
      NULLIF(trim(BOTH FROM idvmodificationnumber), ''),
      NULLIF(trim(BOTH FROM solicitationid), ''),
      NULLIF(trim(BOTH FROM extentcompeted), ''),
      NULLIF(trim(BOTH FROM reasonnotcompeted), ''),
      NULLIF(trim(BOTH FROM numberofoffersreceived), ''),
      NULLIF(trim(BOTH FROM commercialitemacquisitionprocedures), ''),
      NULLIF(trim(BOTH FROM commercialitemtestprogram), ''),
      NULLIF(trim(BOTH FROM smallbusinesscompetitivenessdemonstrationprogram), ''),
      NULLIF(trim(BOTH FROM a76action), ''),
      NULLIF(trim(BOTH FROM competitiveprocedures), ''),
      NULLIF(trim(BOTH FROM solicitationprocedures), ''),
      NULLIF(trim(BOTH FROM typeofsetaside), ''),
      NULLIF(trim(BOTH FROM localareasetaside), ''),
      NULLIF(trim(BOTH FROM evaluatedpreference), ''),
      NULLIF(trim(BOTH FROM fedbizopps), ''),
      NULLIF(trim(BOTH FROM research), ''),
      NULLIF(trim(BOTH FROM statutoryexceptiontofairopportunity), ''),
      NULLIF(trim(BOTH FROM organizationaltype), ''),
      NULLIF(trim(BOTH FROM numberofemployees), ''),
      NULLIF(trim(BOTH FROM annualrevenue), ''),
      NULLIF(trim(BOTH FROM firm8aflag), ''),
      NULLIF(trim(BOTH FROM hubzoneflag), ''),
      NULLIF(trim(BOTH FROM sdbflag), ''),
      NULLIF(trim(BOTH FROM issbacertifiedsmalldisadvantagedbusiness), ''),
      NULLIF(trim(BOTH FROM shelteredworkshopflag), ''),
      NULLIF(trim(BOTH FROM hbcuflag), ''),
      NULLIF(trim(BOTH FROM educationalinstitutionflag), ''),
      NULLIF(trim(BOTH FROM womenownedflag), ''),
      NULLIF(trim(BOTH FROM veteranownedflag), ''),
      NULLIF(trim(BOTH FROM srdvobflag), ''),
      NULLIF(trim(BOTH FROM localgovernmentflag), ''),
      NULLIF(trim(BOTH FROM minorityinstitutionflag), ''),
      NULLIF(trim(BOTH FROM aiobflag), ''),
      NULLIF(trim(BOTH FROM stategovernmentflag), ''),
      NULLIF(trim(BOTH FROM federalgovernmentflag), ''),
      NULLIF(trim(BOTH FROM minorityownedbusinessflag), ''),
      NULLIF(trim(BOTH FROM apaobflag), ''),
      NULLIF(trim(BOTH FROM tribalgovernmentflag), ''),
      NULLIF(trim(BOTH FROM baobflag), ''),
      NULLIF(trim(BOTH FROM naobflag), ''),
      NULLIF(trim(BOTH FROM saaobflag), ''),
      NULLIF(trim(BOTH FROM nonprofitorganizationflag), ''),
      NULLIF(trim(BOTH FROM isothernotforprofitorganization), ''),
      NULLIF(trim(BOTH FROM isforprofitorganization), ''),
      NULLIF(trim(BOTH FROM isfoundation), ''),
      NULLIF(trim(BOTH FROM haobflag), ''),
      NULLIF(trim(BOTH FROM ishispanicservicinginstitution), ''),
      NULLIF(trim(BOTH FROM emergingsmallbusinessflag), ''),
      NULLIF(trim(BOTH FROM hospitalflag), ''),
      NULLIF(trim(BOTH FROM contractingofficerbusinesssizedetermination), ''),
      NULLIF(trim(BOTH FROM is1862landgrantcollege), ''),
      NULLIF(trim(BOTH FROM is1890landgrantcollege), ''),
      NULLIF(trim(BOTH FROM is1994landgrantcollege), ''),
      NULLIF(trim(BOTH FROM isveterinarycollege), ''),
      NULLIF(trim(BOTH FROM isveterinaryhospital), ''),
      NULLIF(trim(BOTH FROM isprivateuniversityorcollege), ''),
      NULLIF(trim(BOTH FROM isschoolofforestry), ''),
      NULLIF(trim(BOTH FROM isstatecontrolledinstitutionofhigherlearning), ''),
      NULLIF(trim(BOTH FROM isserviceprovider), ''),
      NULLIF(trim(BOTH FROM receivescontracts), ''),
      NULLIF(trim(BOTH FROM receivesgrants), ''),
      NULLIF(trim(BOTH FROM receivescontractsandgrants), ''),
      NULLIF(trim(BOTH FROM isairportauthority), ''),
      NULLIF(trim(BOTH FROM iscouncilofgovernments), ''),
      NULLIF(trim(BOTH FROM ishousingauthoritiespublicortribal), ''),
      NULLIF(trim(BOTH FROM isinterstateentity), ''),
      NULLIF(trim(BOTH FROM isplanningcommission), ''),
      NULLIF(trim(BOTH FROM isportauthority), ''),
      NULLIF(trim(BOTH FROM istransitauthority), ''),
      NULLIF(trim(BOTH FROM issubchapterscorporation), ''),
      NULLIF(trim(BOTH FROM islimitedliabilitycorporation), ''),
      NULLIF(trim(BOTH FROM isforeignownedandlocated), ''),
      NULLIF(trim(BOTH FROM isarchitectureandengineering), ''),
      NULLIF(trim(BOTH FROM isdotcertifieddisadvantagedbusinessenterprise), ''),
      NULLIF(trim(BOTH FROM iscitylocalgovernment), ''),
      NULLIF(trim(BOTH FROM iscommunitydevelopedcorporationownedfirm), ''),
      NULLIF(trim(BOTH FROM iscommunitydevelopmentcorporation), ''),
      NULLIF(trim(BOTH FROM isconstructionfirm), ''),
      NULLIF(trim(BOTH FROM ismanufacturerofgoods), ''),
      NULLIF(trim(BOTH FROM iscorporateentitynottaxexempt), ''),
      NULLIF(trim(BOTH FROM iscountylocalgovernment), ''),
      NULLIF(trim(BOTH FROM isdomesticshelter), ''),
      NULLIF(trim(BOTH FROM isfederalgovernmentagency), ''),
      NULLIF(trim(BOTH FROM isfederallyfundedresearchanddevelopmentcorp), ''),
      NULLIF(trim(BOTH FROM isforeigngovernment), ''),
      NULLIF(trim(BOTH FROM isindiantribe), ''),
      NULLIF(trim(BOTH FROM isintermunicipallocalgovernment), ''),
      NULLIF(trim(BOTH FROM isinternationalorganization), ''),
      NULLIF(trim(BOTH FROM islaborsurplusareafirm), ''),
      NULLIF(trim(BOTH FROM islocalgovernmentowned), ''),
      NULLIF(trim(BOTH FROM ismunicipalitylocalgovernment), ''),
      NULLIF(trim(BOTH FROM isnativehawaiianownedorganizationorfirm), ''),
      NULLIF(trim(BOTH FROM isotherbusinessororganization), ''),
      NULLIF(trim(BOTH FROM isotherminorityowned), ''),
      NULLIF(trim(BOTH FROM ispartnershiporlimitedliabilitypartnership), ''),
      NULLIF(trim(BOTH FROM isschooldistrictlocalgovernment), ''),
      NULLIF(trim(BOTH FROM issmallagriculturalcooperative), ''),
      NULLIF(trim(BOTH FROM issoleproprietorship), ''),
      NULLIF(trim(BOTH FROM istownshiplocalgovernment), ''),
      NULLIF(trim(BOTH FROM istriballyownedfirm), ''),
      NULLIF(trim(BOTH FROM istribalcollege), ''),
      NULLIF(trim(BOTH FROM isalaskannativeownedcorporationorfirm), ''),
      NULLIF(trim(BOTH FROM iscorporateentitytaxexempt), ''),
      NULLIF(trim(BOTH FROM iswomenownedsmallbusiness), ''),
      NULLIF(trim(BOTH FROM isecondisadvwomenownedsmallbusiness), ''),
      NULLIF(trim(BOTH FROM isjointventurewomenownedsmallbusiness), ''),
      NULLIF(trim(BOTH FROM isjointventureecondisadvwomenownedsmallbusiness), ''),
      NULLIF(trim(BOTH FROM walshhealyact), ''),
      NULLIF(trim(BOTH FROM servicecontractact), ''),
      NULLIF(trim(BOTH FROM davisbaconact), ''),
      NULLIF(trim(BOTH FROM clingercohenact), ''),
      NULLIF(trim(BOTH FROM otherstatutoryauthority), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive1), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive1_compensation), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive2), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive2_compensation), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive3), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive3_compensation), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive4), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive4_compensation), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive5), ''),
      NULLIF(trim(BOTH FROM prime_awardee_executive5_compensation), ''),
      NULLIF(trim(BOTH FROM interagencycontractingauthority), ''),
      NULLIF(trim(BOTH FROM last_modified_date), '')
    FROM temp_contract
   ON CONFLICT (unique_transaction_id, last_modified_date)
    DO NOTHING;
END
$$ LANGUAGE plpgsql;

select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2000_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2001_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2002_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2003_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2004_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2005_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2006_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2007_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2008_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2009_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2010_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2011_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2012_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2013_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2014_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2015_DOD_Contracts_Full_20160815.csv');
select import_contract_csv('/home/alex/oc-db/datafeeds/datafeeds/2016_DOD_Contracts_Full_20160815.csv');