update contract
set contractor_congressional_district = upper(contractor_congressional_district);
update contract
set contractor_congressional_district_redundant = upper(contractor_congressional_district_redundant);
update contract
set place_of_performance_congressional_district = upper(place_of_performance_congressional_district);
update contract
set place_of_performance_congressional_district_redundant = upper(place_of_performance_congressional_district_redundant);